# Generated by Django 5.1.4 on 2026-06-13 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fontes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_externo', models.CharField(blank=True, help_text='Identificador único na fonte de origem (para evitar duplicados)', max_length=255)),
                ('titulo', models.CharField(max_length=500)),
                ('url_origem', models.URLField(blank=True)),
                ('orgao_responsavel', models.CharField(blank=True, max_length=255)),
                ('area_cultural', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('prazo_inscricao', models.DateField(blank=True, null=True)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='editais/')),
                ('texto_extraido', models.TextField(blank=True)),
                ('status_processamento_ia', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('resumo_ia', models.TextField(blank=True)),
                ('requisitos_ia', models.JSONField(blank=True, default=dict, help_text='Saída estruturada da IA: elegibilidade, documentos exigidos, prazos, valores, critérios')),
                ('erro_processamento', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fonte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editais', to='fontes.fonte')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
                'ordering': ['-criado_em'],
                'unique_together': {('fonte', 'identificador_externo')},
            },
        ),
    ]
