# Generated by Django 5.1.4 on 2026-06-16 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_grupo_categorias'),
        ('editais', '0002_edital_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='categoria',
            field=models.CharField(blank=True, choices=[('cultural', 'Cultural'), ('licitacao', 'Licitação'), ('bolsa', 'Bolsa / Financiamento'), ('concurso_publico', 'Concurso Público'), ('chamada_pesquisa', 'Chamada de Pesquisa'), ('outros', 'Outros')], default='cultural', help_text='Tipo/categoria do edital identificado pela IA', max_length=20),
        ),
        migrations.CreateModel(
            name='LogEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('scraping_ok', 'Scraping executado'), ('scraping_erro', 'Erro no scraping'), ('ia_processado', 'IA processada'), ('ia_erro', 'Erro na IA'), ('edital_criado', 'Edital criado'), ('prazo_ignorado', 'Edital ignorado (prazo vencido)'), ('acompanhamento_criado', 'Acompanhamento iniciado')], max_length=30)),
                ('mensagem', models.TextField()),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('edital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='editais.edital')),
                ('organizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.organizacao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de evento',
                'verbose_name_plural': 'Logs de eventos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
