# Generated by Django 5.1.4 on 2026-06-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='categorias',
            field=models.JSONField(blank=True, default=list, help_text='Categorias de edital de interesse (lista vazia = todas)'),
        ),
    ]
