# Generated by Django 5.1.4 on 2026-06-13 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('acompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carta_apresentacao', 'Carta de apresentação'), ('projeto', 'Projeto cultural'), ('orcamento', 'Orçamento')], max_length=30)),
                ('conteudo', models.TextField(help_text='Conteúdo em markdown')),
                ('versao', models.PositiveIntegerField(default=1)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutas', to='acompanhamento.acompanhamentoedital')),
            ],
            options={
                'verbose_name': 'Minuta',
                'verbose_name_plural': 'Minutas',
                'ordering': ['-gerado_em'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carta_apresentacao', 'Carta de apresentação'), ('projeto', 'Projeto cultural'), ('orcamento', 'Orçamento')], max_length=30)),
                ('nome', models.CharField(max_length=255)),
                ('instrucoes_extra', models.TextField(blank=True, help_text='Instruções adicionais para a IA considerar ao gerar este tipo de documento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('organizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accounts.organizacao')),
            ],
            options={
                'verbose_name': 'Template de documento',
                'verbose_name_plural': 'Templates de documento',
            },
        ),
    ]
