# Generated by Django 5.1.4 on 2026-06-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('mapas_cultural', 'Mapas Culturais (instância)'), ('manual', 'Cadastro manual'), ('outro', 'Outra fonte (sem busca automática)')], default='mapas_cultural', max_length=20)),
                ('url_base', models.URLField(blank=True, help_text='URL base da instância (ex: https://mapacultural.secult.ce.gov.br)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Parâmetros específicos do scraper, ex: {"limite": 30}')),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('ultimo_resultado', models.TextField(blank=True, help_text='Resumo da última execução (quantidade encontrada, erros, etc.)')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fonte',
                'verbose_name_plural': 'Fontes',
                'ordering': ['nome'],
            },
        ),
    ]
