# Generated by Django 5.1.4 on 2026-06-13 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('editais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em análise'), ('elegivel', 'Elegível'), ('inscrito', 'Inscrito'), ('concluido', 'Concluído'), ('descartado', 'Descartado')], default='novo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='editais.edital')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='accounts.organizacao')),
            ],
            options={
                'verbose_name': 'Acompanhamento',
                'verbose_name_plural': 'Acompanhamentos',
                'ordering': ['-criado_em'],
                'unique_together': {('organizacao', 'edital')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('anexado', 'Anexado'), ('ok', 'OK')], default='pendente', max_length=10)),
                ('arquivo_anexo', models.FileField(blank=True, null=True, upload_to='checklist/')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='acompanhamento.acompanhamentoedital')),
            ],
            options={
                'verbose_name': 'Item de checklist',
                'verbose_name_plural': 'Itens de checklist',
                'ordering': ['id'],
            },
        ),
    ]
